version: "2.3"

services:
  percona-mysql:
    percona/percona-server:8.0
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - CLUSTER_NAME=app-cluster
    - XTRABACKUP_PASSWORD=root@123
  ports:
    - 3306:3306
  

#  2 instances of applications on diff host ports
  webapp1:
    image: "web"
    build:
      dockerfile: app/Dockerfile
    ports: 
       - 8081:80
    links:
       - percona-mysql:percona-mysql
    depends_on:
       - percona-mysql

  webapp2:
    image: "web" 
    build:
      dockerfile: app/Dockerfile       
    ports:
       - 8082:80
    links:
       - percona-mysql:percona-mysql
    depends_on:
       - percona-mysql
 

 # Loadbalancer
  nginx:
    image: "nginx"
    build:
      dockerfile: nginx/Dockerfile
    ports:
       - 85:80
    depends_on:
       - percona-mysql
       - webapp1
       - webapp2  